- name: Pull latest simple-api image
  community.docker.docker_image:
    name: rostom78/tp-devops-simple-api:latest
    source: pull

- name: Run simple-api container
  community.docker.docker_container:
    name: simple-api
    image: rostom78/tp-devops-simple-api:latest
    state: started
    recreate: true  # pour forcer la recréation à chaque fois
    pull: yes       # ce champ fonctionne aussi dans docker_container
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: "{{ spring_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ spring_password }}"
    ports:
      - "8080:8080"
    networks:
      - name: myapp_network

