- name: Copy Nginx config file
  copy:
    src: default.conf
    dest: /home/admin/nginx/default.conf
    force: yes
- name: Run Nginx proxy container
  docker_container:
    name: myproxy
    image: rostom78/tp-devops-httpd:latest
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /home/admin/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - name: myapp_network

