- name: Pull latest proxy image
  community.docker.docker_image:
    name: rostom78/tp-devops-httpd:latest
    source: pull

- name: Run proxy container
  community.docker.docker_container:
    name: myproxy
    image: rostom78/tp-devops-httpd:latest
    state: started
    recreate: true
    pull: yes
    ports:
      - "80:80"
    volumes:
      - /home/admin/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - name: myapp_network

